version: "3.7"

networks:
    proxy:
        external: true

services:
    #  Renomear para nome da aplicação
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php.${APP_NAME}
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - proxy

    nginx:
        image: nginx:stable-alpine
        container_name: nginx.${APP_NAME}
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - proxy
